include ../common.mk

nwsrc = filename.nw

all: lib tex

lib: $(header) $(obj)
	$(AR) rcs $(libsrc) $(obj)

python: $(nwsrc)
	$(TANGLE) -Rceo.pxd $(nwsrc) >> $(CEOPATH)/python/ceo.pxd
	$(TANGLE) -Rceo.pyx $(nwsrc) >> $(CEOPATH)/python/ceo.pyx

tex: $(texsrc)

clean:
	rm -f $(obj) $(header) *.*~

cleanbins:
	rm -f bins/*

