include ../common.mk

nwsrc = filename.nw

all: src lib tex

src: $(nwsrc) $(header)

lib: $(obj)
	$(AR) rcs $(libsrc) $(obj)

python: $(nwsrc)
	$(TANGLE) -Rceo.pxd $(nwsrc) >> $(CEOPYPATH)/ceo.pxd
	$(TANGLE) -Rceo.pyx $(nwsrc) >> $(CEOPYPATH)/ceo.pyx

tex: $(texsrc)

clean:
	rm -f $(obj) $(header) *.*~ *.tex

cleanbins:
	rm -f bins/*

