nwsrc = filename.nw
include ../common.mk

all: src lib tex

src: $(nwsrc) $(header)

lib: $(obj)
#	$(AR) rcs $(libsrc) $(obj)

cysrc: $(nwcysrc) $(pxdcysrc) $(pyxcysrc)

cylib:
	make -C $(CEOPYPATH) $(sobj)

tex: $(texsrc)

cytex: $(texcysrc)

cleanpython:
	rm -f *.pxd *.pyx *.so

clean:
	rm -f $(obj) $(header) *.*~ *.tex *.pxd *.pyx *.so

cleanbins:
	rm -f bins/*

