#!/bin/sh
#conda update anaconda
#conda update jupyter
#conda update ipython
#conda update notebook

#cd /mnt/bins/
#wget https://s3-us-west-1.amazonaws.com/gmto.rconan/gmtAtmosphereL060.zip
#unzip gmtAtmosphereL060.zip
sudo mkdir /mnt/simul_results/
sudo chown ubuntu /mnt/simul_results/

cd /home/ubuntu/Dropbox/CEO/simul_scripts_test/
scp -p -i /home/ubuntu/fquiros/awsdos.pem.txt ubuntu@52.8.44.47:/home/ubuntu/fquiros/datadisk/201702-highOrderAO/IntMats/IM_SHgeom_Karhunen-Loeve_nmode300_SHthr0.2.npz .
scp -p -i /home/ubuntu/fquiros/awsdos.pem.txt ubuntu@52.8.44.47:/home/ubuntu/fquiros/datadisk/201702-highOrderAO/IntMats/IM_SHgeom_Karhunen-Loeve_nmode91_SHthr0.2.npz .

for mag in 13.0 13.5 12.5
do
   for angle in 9.5
   do
      cd /home/ubuntu/Dropbox/CEO/simul_scripts_test/
      python set_batch_params.py $mag $angle
      now=`date +"%Y%m%d%H%M%S"`
      echo $now
      filename="/mnt/simul_results/Phasing_Ctrl_$now.zip"
      echo $filename
      cp Phasing_in_AO_mode_params.py /mnt/simul_results/
      env PYTHONPATH=/home/ubuntu/CEO/python/ jupyter nbconvert --to markdown --ExecutePreprocessor.timeout=-1 --NbConvertApp.output_files_dir='/mnt/simul_results/figures/' --execute Phasing_control_in_AO_mode.ipynb
      echo $filename
      mv Phasing_Ctrl.log Phasing_control_in_AO_mode.md /mnt/simul_results/
      cd /mnt/simul_results/
      zip $filename Phasing_Ctrl.log Phasing_in_AO_mode_params.py simul_results.npz figures/* Phasing_control_in_AO_mode.md
      scp -p -i /home/ubuntu/fquiros/awsdos.pem.txt $filename ubuntu@52.8.44.47:/home/ubuntu/fquiros/datadisk/201704-DFS_sensitivity_CREDone/Disp5/NoiseLessDet/
      #mv $filename /home/ubuntu/fquiros/datadisk/201702-AGWS_SPS_sensitivity/NSmode/
   done
done
#aws s3 cp $filename s3://gmto.rconan/AcO_Ctrl/
