#!/bin/sh
#cd /mnt/bins/
#wget https://s3-us-west-1.amazonaws.com/gmto.rconan/gmtAtmosphereL060.zip
#unzip gmtAtmosphereL060.zip
cd /home/ubuntu/Dropbox/CEO/simul_scripts_test/
#scp -p -i /home/ubuntu/fquiros/awsdos.pem.txt ubuntu@52.8.44.47:/home/ubuntu/fquiros/datadisk/201702-highOrderAO/IntMats/IM_SHgeom_Karhunen-Loeve_nmode300_SHthr0.2.npz .
for i in 0 1 2 3 4 5 6 7 8
do
   python set_simulation_params.py $i
   now=`date +"%Y%m%d%H%M%S"`
   echo $now
   filename="Phasing_Ctrl_$now.zip"
   echo $filename
   env PYTHONPATH=/home/ubuntu/CEO/python/ jupyter nbconvert --to markdown --ExecutePreprocessor.timeout=-1 --execute Phasing_control_in_AO_mode.ipynb
   zip $filename Phasing_Ctrl.log Phasing_in_AO_mode_params.py simul_results.npz Phasing_control_in_AO_mode_files/* Phasing_control_in_AO_mode.md
   #scp -p -i /home/ubuntu/fquiros/awsdos.pem.txt $filename ubuntu@52.8.44.47:/home/ubuntu/fquiros/datadisk/201702-AGWS_SPS_sensitivity/NSmode/
   mv $filename /home/ubuntu/fquiros/datadisk/201702-AGWS_SPS_sensitivity/LTAOmode/
done
#aws s3 cp $filename s3://gmto.rconan/AcO_Ctrl/
