#define _N_LAYER_ 1
#define _N_PIXEL_ 1000
#define _SOURCE_N_PX_ _N_PIXEL_
#define N_SIDE_LENSLET 1
#define _N_LENSLET_ (N_SIDE_LENSLET*N_SIDE_LENSLET)
#define _N_PX_PUPIL_ 8
#define _N_DFT_ (2*_N_PX_PUPIL_)
#define _N_PX_IMAGE_ _N_DFT_ 
#define _N_PX_CAMERA_ _N_PX_PUPIL_
#define _N_SOURCE_ 1
